name: OneblockUtils
version: '1.0-SNAPSHOT'
main: byrnes.jonathan.OneblockUtils
api-version: '1.21'
softdepend: [SuperiorSkyblock]
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: true
